config/routes.rb
Rails.application.routes.draw do

  resources :pstats

  resources :ctypes

  resources :statuses

  resources :locations

  root 'navigation#home'

  get '/work' => 'navigation#work'

  get '/about' => 'navigation#about'

  get '/contact' => 'navigation#contact'

  get '/clientele' => 'navigation#clientele'

  get '/home' => 'navigation#home'

  get '/console' => 'navigation#console'       

  get '/preview' => 'models#preview'    

  get '/instagram' => 'navigation#instagram'

  get '/portfolio' => 'projects#portfolio'

  devise_scope :admin do 
  get '/nt' => 'devise/sessions#create'
  end               

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :clients do
      resources :projects
    end

    resources :projects do
      resources :photos do
        delete :destroy_multiple, action: :destroy, on: :collection
      end
    end

    resources :projects do

      patch :transform, action: :highlight, on: :collection

    end

  

  devise_for :admins, skip: :registrations
  
  resources :models

  resources :photographers

end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                :integer          not null, primary key
#  email             :string(255)
#  name              :string(255)
#  nameofcontact     :string(255)
#  phonenumber       :string(255)
#  mailingaddress    :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  password_digest   :string(255)
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#

class Client < ActiveRecord::Base

has_attached_file :logo, styles: {
thumb: '150x150>',
square: '200x200#',
}, :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/aws.yml",
    :bucket => "ntpkhi3"


	has_many :projects, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
  	 VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  		validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL },
                    uniqueness: { case_sensitive: false }
     has_secure_password
     validates :password, presence: true, length: { minimum: 6 }

  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/models/ctype.rb
# == Schema Information
#
# Table name: ctypes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Ctype < ActiveRecord::Base
  
	default_scope -> { order('name ASC') }
	validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  project_id :integer
#

class Location < ActiveRecord::Base
	belongs_to :project
	
end

app/models/model.rb
# == Schema Information
#
# Table name: models
#
#  id                  :integer          not null, primary key
#  firstname           :string(255)
#  lastname            :string(255)
#  heightfeet          :integer
#  size                :string(255)
#  shoesize            :float
#  haircolor           :string(255)
#  eyes                :string(255)
#  bust                :float
#  waist               :float
#  hips                :float
#  phonenumber         :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  heightinches        :decimal(, )
#  city                :string(255)
#  age                 :integer
#

class Model < ActiveRecord::Base
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'}, :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/aws.yml",
    :bucket => "ntpkhi3"
 
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :phonenumber, length: { minimum: 10 }, uniqueness: true



  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id                 :integer          not null, primary key
#  project_id         :integer
#  created_at         :datetime
#  updated_at         :datetime
#  asset_file_name    :string(255)
#  asset_content_type :string(255)
#  asset_file_size    :integer
#  asset_updated_at   :datetime
#

class Photo < ActiveRecord::Base
  belongs_to :project

    has_attached_file :asset, styles: {
    thumb: '100x100>',
    square: '200x200#',
    featured: '1200x800',
    preview: '200x300>',
    carousel:""
  }, :convert_options => { :carousel => "-gravity center -crop 1400x720+0+0" }, :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/aws.yml",
    :bucket => "ntpkhi3", default_url: "/images/:style/missing.png"

   
  
  do_not_validate_attachment_file_type :asset
  validates_attachment_size :asset, :less_than => 4.megabytes

  
end

app/models/photographer.rb
# == Schema Information
#
# Table name: photographers
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  email       :string(255)
#  phonenumber :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Photographer < ActiveRecord::Base



	validates :name, presence: true
	



end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id            :integer          not null, primary key
#  date          :date
#  headline      :string(255)
#  location      :string(255)
#  description   :text
#  ctype         :string(255)
#  status        :string(255)
#  paymentstatus :string(255)
#  client_id     :integer
#  created_at    :datetime
#  updated_at    :datetime
#  is_featured   :boolean          default(FALSE)
#  photographer  :string(255)
#

class Project < ActiveRecord::Base
  belongs_to :client
  has_many :locations
  has_many :photos



  validates :client_id, presence: true

 
end

app/models/pstat.rb
# == Schema Information
#
# Table name: pstats
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  project_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Pstat < ActiveRecord::Base
  belongs_to :project
end

app/models/status.rb
# == Schema Information
#
# Table name: statuses
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Status < ActiveRecord::Base

	validates :name, presence: true

	default_scope -> { order('name ASC') }
	
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy]
  before_action :authorized_access, only: [:show, :index]
  respond_to :html

  def index
    @models = Model.all
    respond_with(@models)
  end

  def show
    @model = Model.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
      render pdf: "NTP-#{@model.firstname}-cutsheet"
      end
    end
  end

  def new
    @model = Model.new
    respond_with(@model)
  end

  def preview
    @models = Model.all
  end


  def edit
  end

  def create
    @model = Model.new(model_params)
    @model.save
    respond_with(@model)
  end

  def update
    @model.update(model_params)
    respond_with(@model)
  end

  def destroy
    @model.destroy
    respond_with(@model)
  end

  private
    def set_model
      @model = Model.find(params[:id])
    end

    def model_params
      params.require(:model).permit(:firstname, :lastname, :heightfeet, :heightinches, :size, :shoesize, :haircolor, :eyes, :bust, :waist, :hips, :phonenumber, :city, :age, :avatar)
    end

        def authorized_access
      unless client_signed_in? or admin_signed_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
    end
  end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_for(@model, multipart: true) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" id="containerb">

  <div class="field">
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :heightfeet, "Height:" %> <%= f.select :heightfeet, (0..7).to_a, :label => "Feet" %>
    <%= f.label :heightinches, "Inches" %> <%= f.number_field :heightinches, :step => '0.25' %><br>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
   <div class="field">
    <%= f.label :age, "Age" %><br>
    <%= f.select :age, (1..90).to_a %>  
  </div>
  <div class="field">
    <%= f.label :shoesize, "Shoe Size" %><br>
    <%= f.select :shoesize, ((3..12).step(0.5)).to_a %>
  </div>
  <div class="field">
    <%= f.label :haircolor, "Hair Color" %><br>
    <%= f.select :haircolor, ["Black", "Brown", "White", "Grey", "Blonde", "Red"] %>
  </div>
  <div class="field">
    <%= f.label :eyes %><br>
    <%= f.select :eyes, ["Black", "Brown", "Green", "Grey", "Blue"] %>
  </div>
  <div class="field">
    <%= f.label :bust %><br>
    <%= f.number_field :bust, :step => '0.25'  %>
  </div>
  <div class="field">
    <%= f.label :waist %><br>
    <%= f.number_field :waist, :step => '0.25'  %>
  </div>
  <div class="field">
    <%= f.label :hips %><br>
    <%= f.number_field :hips %>
  </div>

  <% if admin_signed_in? %>

  <div class="field">
    <%= f.label :phonenumber, "Phone Number" %><br>
    <%= f.number_field :phonenumber %>
  </div>

  <% end %>
  
   <div class="field">
    <%= f.label :city, "City" %><br>
    <%= f.select :city, ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi"] %>
  </div>
    <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

</div>

app/views/models/edit.html.erb
<div class="container" id="containerb">

<p class="attn">Editing model</p>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>


</div>

app/views/models/index.html.erb
<div class="container" id="containerb">

<p class="attn">Listing models</p><br>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Hair color</th>
      <th>Eyes</th>
      <th>Bust</th>
      <th>Waist</th>
      <th>Hips</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.firstname %></td>
        <td><%= model.lastname %></td>
        <td><%= model.haircolor %></td>
        <td><%= model.eyes %></td>
        <td><%= model.bust %></td>
        <td><%= model.waist %></td>
        <td><%= model.hips %></td>
        <td><%= link_to 'Show', model %></td>

        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_model_path(model), class: "linktext"  %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure? This action cannot be undone' }, class: "linkdanger"  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

</div>

app/views/models/new.html.erb
<div class="container" id="containerb">

<p class="attn">New model</p>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

</div>

app/views/models/preview.html.erb
<div class="container-fluid" id="containerc">

	<p class="attn"> Preview Page </p>
 


 <% @models.each do |m| %>

<div class="item row"> 
	<div class="bord">
		<%= link_to(image_tag(m.avatar.url(:square)), model_path(m))%>
	</div>
</div>


<% end %>
</div>


<script>
// initialize Isotope
var $container = $('#containerc').isotope({
  itemSelector: '.item',
   masonry: {
    columnWidth: 50
  }
});
// layout Isotope again after all images have loaded
$container.imagesLoaded( function() {
  $container.isotope('layout');
});

</script>

app/views/models/show.html.erb
<div class="container" id="containerb">

<p id="notice"><%= notice %></p>
<div> <%= image_tag @model.avatar.url(:square) %> </div>
<br>
<p>
  <strong>First Name:</strong>
  <%= @model.firstname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @model.lastname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @model.age %>
</p>
<p>
  <strong>Location:</strong>
  <%= @model.city %>
</p>

<p>
  <strong>Height:</strong>
  <%= @model.heightfeet %> Feet 
  <%= @model.heightinches %> Inches
</p>

<p>
  <strong>Size:</strong>
  <%= @model.size %>
</p>

<p>
  <strong>Shoe size:</strong>
  <%= @model.shoesize %>
</p>

<p>
  <strong>Hair color:</strong>
  <%= @model.haircolor %>
</p>

<p>
  <strong>Eyes:</strong>
  <%= @model.eyes %>
</p>

<p>
  <strong>Bust:</strong>
  <%= @model.bust %>
</p>

<p>
  <strong>Waist:</strong>
  <%= @model.waist %>
</p>

<p>
  <strong>Hips:</strong>
  <%= @model.hips %>
</p>

<% if admin_signed_in? %>
<p>
  <strong>Phone number:</strong>
  <%= @model.phonenumber %>
</p>


<div>
<%= link_to 'Edit', edit_model_path(@model), class: "btn btn-sm
 btn-warning" %>
 <% end %>
<%= link_to 'Back', models_path, class: "btn btn-default btn-sm linktext" %> </div><br>
<div><%= link_to 'Download PDF', model_path(@model, :format => "pdf"), :target => '_blank', class: "btn btn-success btn-sm" %><small> PDF file opens in a new window</small></div>

</div>

app/views/models/show.pdf.erb
<h2>NTP - Nadir Toosy Photography</h2><br>


<h4> Model Cutsheet for <%= @model.firstname %> <%= @model.lastname %> </h4><br>

<div> <%= image_tag @model.avatar.url(:square) %> </div>
<br>
<p>
 <strong>First Name:</strong>
  <%= @model.firstname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @model.lastname %>
</p>

<p>
  <strong>Height:</strong>
  <%= @model.heightfeet %> Feet 
  <%= @model.heightinches %> Inches
</p>

<p>
  <strong>Size:</strong>
  <%= @model.size %>
</p>

<p>
  <strong>Shoe size:</strong>
  <%= @model.shoesize %>
</p>

<p>
  <strong>Hair color:</strong>
  <%= @model.haircolor %>
</p>

<p>
  <strong>Eyes:</strong>
  <%= @model.eyes %>
</p>

<p> For rates, measurements, availability and bookings, please contact your project manager at NTP, or send us an email at info@nadirtoosy.com</p>