config/routes.rb
Rails.application.routes.draw do

  resources :pstats

  resources :ctypes

  resources :statuses

  resources :locations

  root 'navigation#home'

  get '/work' => 'navigation#work'

  get '/about' => 'navigation#about'

  get '/contact' => 'navigation#contact'

  get '/clientele' => 'navigation#clientele'

  get '/home' => 'navigation#home'

  get '/console' => 'navigation#console'       

  get '/preview' => 'models#preview'    

  get '/instagram' => 'navigation#instagram'

  get '/portfolio' => 'projects#portfolio'

  devise_scope :admin do 
  get '/nt' => 'devise/sessions#create'
  end               

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :clients do
      resources :projects
    end

    resources :projects do
      resources :photos do
        delete :destroy_multiple, action: :destroy, on: :collection
      end
    end

    resources :projects do

      patch :transform, action: :highlight, on: :collection

    end

  

  devise_for :admins, skip: :registrations
  
  resources :models

  resources :photographers

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                :integer          not null, primary key
#  email             :string(255)
#  name              :string(255)
#  nameofcontact     :string(255)
#  phonenumber       :string(255)
#  mailingaddress    :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  password_digest   :string(255)
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#

class Client < ActiveRecord::Base

has_attached_file :logo, styles: {
thumb: '150x150>',
square: '200x200#',
}, :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/aws.yml",
    :bucket => "ntpkhi3"


	has_many :projects, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
  	 VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  		validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL },
                    uniqueness: { case_sensitive: false }
     has_secure_password
     validates :password, presence: true, length: { minimum: 6 }

  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController


before_action :authenticate_admin!, only: [:index, :edit, :update, :new, :create, :destroy]
before_action :check_client, only: [:show]
#before_action :logged_in_client, only: [:edit, :update]


  def index
  	@clients = Client.paginate(page: params[:page], :per_page => 7)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      log_in @client
      flash[:success] = "Welcome to NTP"
      redirect_to @client
    else
      render 'new'
    end
  end

  def show
     @client = Client.find(params[:id])
     @projects = @client.projects.paginate(page: params[:page])
     @project = @client.projects.find_by(params[:project_id])
  end

  def edit
    @client = Client.find(params[:id])
  end

    def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      flash[:success] = "Settings updated"
      redirect_to @client
    else
      render 'edit'
    end
  end

    def destroy
    Client.find(params[:id]).destroy
    flash[:success] = "Client deleted"
    redirect_to clients_url
  end


private

 def check_client
      @client = Client.find(params[:id])
      redirect_to(root_url) unless @client == current_client or admin_signed_in?
    end

      def client_params
      params.require(:client).permit(:name, :email, :nameofcontact, :phonenumber, :mailingaddress, :password, :password_confirmation, :logo)
    end

    def logged_in_client
      unless client_signed_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<div class="container" id="containerb">

<% provide(:title, 'Edit Client Details') %>

<p class="attn">Edit client information</p>

<br>

    <%= form_for(@client, multipart: true) do |f| %>
    <%= render 'shared/error_messages' %>

   <div> <%= f.label :name %> </div>
   <div> <%= f.text_field :name, autofocus: true  %> </div></br>

      <div> <%= f.label :email, class: 'label1'  %> </div>
      <div> <%= f.email_field :email %> </div></br>

      <div> <%= f.label :nameofcontact, 'Name of Contact', class: 'label1'  %> </div>
      <div> <%= f.text_field :nameofcontact %> </div></br>

      <div> <%= f.label :phonenumber, 'Phone Number', class: 'label1'  %> </div>
      <div> <%= f.text_field :phonenumber %> </div></br>

      <div> <%= f.label :mailingaddress, 'Mailing Address', class: 'label1'  %> </div>
      <div> <%= f.text_field :mailingaddress %> </div></br>

      <div> <%= f.label :password, class: 'label1'  %> </div>
      <div> <%= f.password_field :password %> </div></br>

      <div> <%= f.label :password_confirmation, "Confirmation", class: 'label1'  %> </div>
      <div> <%= f.password_field :password_confirmation %> </div></br>

      <div class="field">
        <%= f.label :logo, class: 'label1'  %>
        <%= f.file_field :logo %>
      </div></br>

     <div> <%= f.submit "Save changes", class: "btn btn-success btn-sm" %> </div>
    <% end %>
  </div>
</div>
</div>

app/views/clients/index.html.erb
<div class="container" id="containerb">

<p class="attn">Client Index (<%= @clients.count %>)</p> <br>




<table class="table table-hover table-condensed">
<thead> 
    <tr>
      <th>Client name</th>
      <th># of Projects</th>
      <th>Email address</th>
      <th>Phone Number</th>
      <th>Edit</th>
      <th>Delete</th>
    
    </tr>
  </thead>


    <tbody> 
     <% @clients.each do |client| %>
    <tr>
    <td><%= link_to client.name, client_path(client), class: "linktext" %></td>
    <td><%= client.projects.count %></td>
    <td><%= client.email %></td>
    <td><%= client.phonenumber %></td>

<% if admin_signed_in? && !client_signed_in? %>
  <td><%= link_to "edit", edit_client_path(client), class: "linktext" %></td>    
  <td><%= link_to "delete", client, method: :delete, data: { confirm: "Are you sure? This action cannot be undone." }, class: "linkdanger" %></td>
<% end %>
    </tr>
    </tbody>
  
  <% end %>
</table>

<%= will_paginate %>

</div>

app/views/clients/new.html.erb
<div class="container" id="containerb">

<% provide(:title, 'Sign up') %>

<p class="attn">Add New Client</p>

<br>

    <%= form_for(@client, multipart: true) do |f| %>
    <%= render 'shared/error_messages' %>

<div>  <%= f.label :name, 'Client Name', class: 'label1' %> </div>
<div>  <%= f.text_field :name, autofocus: true  %> </div> </br>

<div> <%= f.label :email, class: 'label1' %> </div>
<div> <%= f.email_field :email %> </div> </br>

<div> <%= f.label :nameofcontact, 'Name of Contact', class: 'label1' %> </div>
<div> <%= f.text_field :nameofcontact %> </div> </br>

<div> <%= f.label :phonenumber, 'Phone Number', class: 'label1' %> </div>
<div> <%= f.text_field :phonenumber %> </div> </br>

<div> <%= f.label :mailingaddress, 'Mailing Address', class: 'label1' %> </div>
<div> <%= f.text_field :mailingaddress %> </div> </br>

<div> <%= f.label :password, class: 'label1' %> </div>
<div> <%= f.password_field :password %> </div> </br>

<div> <%= f.label :password_confirmation, "Password Confirmation", class: 'label1' %> </div>
<div> <%= f.password_field :password_confirmation %> </div> </br>

<div class="field">
      <%= f.label :logo, class: 'label1' %>
      <%= f.file_field :logo %>
</div>
</br>

      <%= f.submit "Create new client", class: "btn btn-success btn-sm" %>
    <% end %>
</div>

app/views/clients/show.html.erb
<div class="container" id="containerb">

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= image_tag @client.logo.url(:square) %>
     <div>
      <%= @client.name %>, <%= @client.email %> 
    </div>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @client.projects.any? %>
      <p class="attn">Projects (<%= @client.projects.count %>)</p>
    <% @client.projects.each do |x| %>
  <ul>
    <li><%= link_to x.client.name, x.client %> | <%= x.description %> | Project ID: <%= x.id %> |<%= link_to "project details", client_project_path(@client, x), class: "btn btn-link linktext" %> |<%if admin_signed_in?%> <%= link_to "edit", edit_client_project_path(@client,x), class: "btn btn-link linktext" %><% end %><small> Created <%= time_ago_in_words(x.created_at) %> ago.</small></li> 
  </ul>
  <% end %>

      <%= will_paginate @projects %>
    <% end %>
  </div>
</div>

<div>
  <% if admin_signed_in? %>
  <%= link_to "Create new project", new_client_project_path(@client), class: 'btn btn-default btn-sm linktext' %> <% end %>
  <%= link_to 'Back', :back, class: "btn btn-default btn-sm linktext" %>
</div>

</end>