config/routes.rb
Rails.application.routes.draw do

  resources :pstats

  resources :ctypes

  resources :statuses

  resources :locations

  root 'navigation#home'

  get '/work' => 'navigation#work'

  get '/about' => 'navigation#about'

  get '/contact' => 'navigation#contact'

  get '/clientele' => 'navigation#clientele'

  get '/home' => 'navigation#home'

  get '/console' => 'navigation#console'       

  get '/preview' => 'models#preview'    

  get '/instagram' => 'navigation#instagram'

  get '/portfolio' => 'projects#portfolio'

  devise_scope :admin do 
  get '/nt' => 'devise/sessions#create'
  end               

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :clients do
      resources :projects
    end

    resources :projects do
      resources :photos do
        delete :destroy_multiple, action: :destroy, on: :collection
      end
    end

    resources :projects do

      patch :transform, action: :highlight, on: :collection

    end

  

  devise_for :admins, skip: :registrations
  
  resources :models

  resources :photographers

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id            :integer          not null, primary key
#  date          :date
#  headline      :string(255)
#  location      :string(255)
#  description   :text
#  ctype         :string(255)
#  status        :string(255)
#  paymentstatus :string(255)
#  client_id     :integer
#  created_at    :datetime
#  updated_at    :datetime
#  is_featured   :boolean          default(FALSE)
#  photographer  :string(255)
#

class Project < ActiveRecord::Base
  belongs_to :client
  has_many :locations
  has_many :photos



  validates :client_id, presence: true

 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_admin!, only: [:new, :index, :create, :destroy, :details, :edit]

	def index
	@projects = Project.all
	end


	def new
		@client = Client.find(params[:client_id])
		@project = Project.new
	end

	def create
		@client = Client.find(params[:client_id])
		@project = @client.projects.build(project_params)
		if @project.save
			flash[:success] = "New project created!"
			redirect_to client_path(@client)
		else
			render admin_path
		end
	end

	def destroy
		@client = Client.find(params[:client_id])
		@project = @client.projects.find(params[:id])

		@project.destroy
    	flash[:success] = "Project deleted"
    	redirect_to client_path(@client)
	end

	def show
		@client = Client.find(params[:client_id])
		@project = Project.find(params[:id])
		@photo = @project.photos.find_by(params[:photo_id])
	end

	def highlight
	Project.where(id: params[:showreel]).update_all(is_featured: true)
 		 redirect_to projects_path 	
	end


  def edit
  	  @client = Client.find(params[:client_id])
 	  @project = Project.find(params[:id])
  end




  def update
  


if params[:showreel].nil?
	@client = Client.find(params[:client_id])
  @project = Project.find(params[:id])

	@project.update_attributes(project_params)
      				flash[:success] = "Settings updated"
      				redirect_to projects_path

elsif params[:showreel].any?

@allprojects = Project.all
@allprojects.update_all(is_featured: false)

  		project_ids = params[:showreel]
  			project_ids.each do |x|
  				
  				@project = Project.find_by_id(x)
  				@project.update_attribute(:is_featured, true)
  				@project.save
  				
  				end
  				redirect_to projects_path
  			end
  		end

	private

	def project_params
		params.require(:project).permit(:date, :headline, :location, :description, :photographer, :ctype, :status, :paymentstatus, :is_featured, :card)
	end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li id="project-<%= project.id %>">

	<% @client.projects.each do |x| %>
	<ul>
		<li><%= link_to x.client.name, x.client %> | <%= x.description %> | <%= link_to "project details", client_project_path(@client, x), class: "btn btn-link linktext" %> | <%= link_to "add photos", new_photo_path(@client, x), class: "btn btn-link linktext" %>  | <small> Created <%= time_ago_in_words(x.created_at) %> ago.</small></li> 
	</ul>
	<% end %>
</div>

app/views/projects/edit.html.erb
<div class="container" id="containerb">

<br>

<p class="attn"> Edit a <%= @client.name %> project </p>

</br>

<div>
<%= form_for ([@client, @project]) do |f| %>
<%= render 'shared/error_messages' %>


  <div> 
    <%= f.label :ctype, "Category", class: 'label1' %>
    <%= f.collection_select(:ctype, Ctype.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :location, class: 'label1' %>
    <%= f.collection_select(:location, Location.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :description, class: 'label1' %>
	  <%= f.text_area :description, size: "60x7", class: 'formalign' %>
	</div>
<br>

  <div> 
    <%= f.label :headline, class: 'label1' %>
	  <%= f.text_field :headline, class: 'formalign' %>
	</div>
<br>
 <div> 
    <%= f.label :photographer, class: 'label1' %>
    <%= f.collection_select(:photographer, Photographer.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :status, class: 'label1' %>
    <%= f.collection_select(:status, Status.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :paymentstatus, "Payment Status", class: 'label1' %>
    <%= f.collection_select(:paymentstatus, Pstat.all, :name, :name) %>
  </div>
<br>
 <div><%= f.label :card, "Create card for portfolio?", class: 'label1' %>
       <%= f.check_box :card %>
     </div>
  <br>


<div>
    <%= f.submit "Update project", class: "btn btn-success btn-sm" %>
    <%= link_to 'Back', :back, class: "btn btn-default btn-sm linktext" %>
</div>

    <% end %>

  </div>

</div>

app/views/projects/highlight.html.erb
<%= form_tag set_featured_projects_path, method: :patch do %>
<ul class="consolebox">
<% @projects.each do |p| %>
<li>
<%= check_box_tag 'showreel[]', p.id %>
<%= x.id %> 
</li>
<% end %>
</ul>
</br>
<%= submit_tag "Set as featured", class: "btn btn-danger btn-sm" %>
<% end %>


</div>

app/views/projects/index.html.erb
<div class="container" id="containerb">

<p class="attn">Listing Projects</p><br>
<%= form_tag transform_projects_path, method: :patch do %>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Client Name</th>
      <th>Project ID</th>
      <th>Project date</th>
      <th>Category</th>
      <th>Status</th>
      <th>Client ID</th>
      <th>Featured</th>
      <th>Feature?</th>
      <th> colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |x| %>
      <tr>
        <td><%= x.client.name %></td>
        <td><%= x.id %></td>
        <td><%= x.date %></td>
        <td><%= x.ctype %></td>
        <td><%= x.status %></td>
        <td><%= x.client_id %></td>
        <td><%= t x.is_featured.class %></td>
        <td><%= check_box_tag 'showreel[]', x.id %></td>




      </tr>

    <% end %>


  </tbody>
</table>

<br>




</ul>


</br>
<%= submit_tag "Set as featured", class: "btn btn-success btn-sm" %>
<% end %>



</div>
</div>

app/views/projects/new.html.erb
<div class="container" id="containerb">

<br>

<p class="attn"> Create a new project for <%= @client.name %> </p>

</br>

<div>
<%= form_for ([@client, @project]) do |f| %>
<%= render 'shared/error_messages' %>

  <div> 
    <%= f.label :date, class: 'label1' %>
    <%= f.date_field :date, :value => Time.zone.now.to_date.strftime("%B %d, %Y"), :readonly => true, class: "borderless"  %>
  </div>
<br>

  <div> 
    <%= f.label :ctype, "Category", class: 'label1' %>
    <%= f.collection_select(:ctype, Ctype.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :location, class: 'label1' %>
    <%= f.collection_select(:location, Location.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :description, class: 'label1' %>
	  <%= f.text_area :description, size: "60x7", class: 'formalign' %>
	</div>
<br>

  <div> 
    <%= f.label :photographer, class: 'label1' %>
    <%= f.collection_select(:photographer, Photographer.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :status, class: 'label1' %>
    <%= f.collection_select(:status, Status.all, :name, :name) %>
  </div>
<br>

  <div> 
    <%= f.label :paymentstatus, "Payment Status", class: 'label1' %>
    <%= f.collection_select(:paymentstatus, Pstat.all, :name, :name) %>
  </div>
<br>
  <div><%= f.label :card, "Create card for portfolio?", class: 'label1' %>
       <%= f.check_box :card %>
     </div>
  <br>

<div>
    <%= f.submit "Create new project", class: "btn btn-success btn-sm" %>
    <%= link_to 'Back', :back, class: "btn btn-default btn-sm linktext" %>
</div>

    <% end %>

  </div>

</div>

app/views/projects/show.html.erb
<div class="container" id="containerb">

	<div class="row">
		<div class="col-md-5">

<p class="attn"> Project Details </p>

<hr>
<br>

<div class="logoborder"><%= image_tag(@project.client.logo(:thumb)) %></div>



<div> Client Name: <%= @client.name %> </div>

<br>

<div> Project Created on: <%= @project.date %> </div>

<br>

<div> Client Representative: <%= @client.nameofcontact %> </div>

<br>

<div> Client ID: <%= @client.id %> </div>

<br>

<div> Project ID: <%= @project.id %> </div>

<br>

<div> Project Type: <%= @project.ctype %> </div>

<br>

<div> Project Location: <%= @project.location %> </div>

<br>

<div> Project Status: <%= @project.status %> </div>

<br>

<div> Payment Status: <%= @project.paymentstatus %> </div>


<br>
<br>
<div>
  <%= link_to "Add Photos to Project", new_project_photo_path(@project), class: "btn btn-default btn-sm" %>

  <% if @project.photos.any? %>

<%= link_to "View Photos", project_photo_path(@project, @photo), class: "btn btn-default btn-sm" %>

<% end %>

</div>

<br>

<%= link_to client_path(@client), class: "btn btn-default btn-sm linktext" do %> 
<span class="glyphicon glyphicon-arrow-left"></span> Back to Client Profile page
<% end %>

<% if admin_signed_in? %>

<%= link_to 'Delete', "#", method: :delete, data: { confirm: 'Deleting this project will also permanently delete all images associated with this project. Are you sure you wish to proceed?' }, class: "btn btn-danger btn-sm" %>

<% end %>

</div>


<div class="col-md-7">

	<p class="attn"> Project Thumbnails </p>

<hr>
<br>

<% @project.photos.each do |x| %>

<%= image_tag(x.asset.url(:thumb)) %> 

<% end %>

</br>
</br>

<% if @project.photos.any? %>

<small><em> To see larger images or remove any/all of the current images for this project, please click on "View Photos" in the Project Details menu. To add additional images, please click on the "Add Photos to Project" button. </em></small>

<% else %>

<small><em> This project currently does not have any images associated with it." To add imagery, please click on the "Add Photos to Project" button in the Project Details menu. </em></small>

<% end %>

</div>
</div>

app/views/projects/update.html.erb
s