config/routes.rb
Rails.application.routes.draw do

  resources :pstats

  resources :ctypes

  resources :statuses

  resources :locations

  root 'navigation#home'

  get '/work' => 'navigation#work'

  get '/about' => 'navigation#about'

  get '/contact' => 'navigation#contact'

  get '/clientele' => 'navigation#clientele'

  get '/home' => 'navigation#home'

  get '/console' => 'navigation#console'       

  get '/preview' => 'models#preview'    

  get '/instagram' => 'navigation#instagram'

  get '/portfolio' => 'projects#portfolio'

  devise_scope :admin do 
  get '/nt' => 'devise/sessions#create'
  end               

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :clients do
      resources :projects
    end

    resources :projects do
      resources :photos do
        delete :destroy_multiple, action: :destroy, on: :collection
      end
    end

    resources :projects do

      patch :transform, action: :highlight, on: :collection

    end

  

  devise_for :admins, skip: :registrations
  
  resources :models

  resources :photographers

end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController
  
  def home

    @featuredprojects = Project.where("is_featured = ?", true)

    @projectpreview = Project.all

    @z = @projectpreview.sample(4)

  end

  def work

    @projects = Project.where(card: true).order('created_at DESC')
    @ctypes = Ctype.all

  end



  def about
  	respond_to do |format|
       format.html { render layout: !request.xhr? }
    end
  end



  def contact
  end



  def clientele

    @clients = Client.all
  
  end



  def console

    @photographers = Photographer.all
    @models = Model.all
    @clients = Client.all
    @ctypes = Ctype.all
    @locations = Location.all
    @statuses = Status.all
    @pstat = Pstat.all
    
  end



  def instagram

    @feed = HTTParty.get("https://api.instagram.com/v1/users/self/media/recent/?access_token=#{Instagram.access_token}")
    @fi = @feed.parsed_response

  end

private



end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/views/navigation/about.html.erb
<div class="container-fluid" id="containeri">

	<div class="container">

<p class="attn"> About NTP </p>


	<h6> Oops...You over-eager sod. This section isn't ready yet. Hush along now! </h6>

</div>

</div>

app/views/navigation/clientele.html.erb
<div class="container" id="containerb">


  <% @clients.each do |client| %>

 <div class="item row">
  <%= image_tag(client.logo.url(:thumb), class: "logoshowcase") %>
 </div>

<% end %>



</div>

<script>


var $container = $('#containerb').isotope({
  itemSelector: '.item',
   masonry: {
    columnWidth: 50
  }
});

$container.imagesLoaded( function() {
  $container.isotope('layout');
});

</script>

app/views/navigation/console.html.erb
<div class="container" id="containerb">


<% if admin_signed_in? %>

<div class="row">

	<div class="col-md-6">
	</br>
		<p class="attn"> Projects by Category </p>
		<%= pie_chart Project.group(:ctype).count %>
	
	</div>

	<div class="col-md-3">

		<div class="square" id="cone"> 
			<div class="consoleboxtitle"> Model Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all models", models_path %> (<%= @models.count %>) </li>
		<li><%=link_to "Add new model", new_model_path%></li>
		<li><%=link_to "Models preview page", preview_path%></li>
		</ul>
		</div>

		<div class="square" id="ctwo"> 
		<div class="consoleboxtitle"> Photographer Management</div>
		<ul class="consolebox">
		<li><%=link_to "View all photographers", photographers_path %> (<%= @photographers.count %>) </li>
		<li><%=link_to "Add new photographer", new_photographer_path%></li>
		</ul>
		</div>

		<div class="square" id="cthree"> 
		<div class="consoleboxtitle">  Client Management </div>
		<ul class="consolebox">
		<li><%= link_to "View all clients",    clients_path %> (<%= @clients.count %>) </li>
		<li><%=link_to "Add new client", new_client_path%></li>
		</ul>
		</div>

		<div class="square" id="cfour"> 
		<div class="consoleboxtitle"> Category Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all categories", ctypes_path %> (<%= @ctypes.count %>) </li>
		<li><%=link_to "Add new category", new_ctype_path %></li>
		</ul>
		</div>

	</div>

	<div class="col-md-3">

		<div class="square" id="cfive"> 
		<div class="consoleboxtitle"> Location Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all locations", locations_path %> (<%= @locations.count %>) </li>
		<li><%=link_to "Add new location", new_location_path %></li>
		</ul>
		</div>

		<div class="square" id="csix"> 
		<div class="consoleboxtitle"> Project Status Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all Statuses", statuses_path %> (<%= @statuses.count %>) </li>
		<li><%=link_to "Add new Status", new_status_path %></li>
		</ul>
		</div>

		<div class="square" id="cseven"> 
		<div class="consoleboxtitle"> Payment Status Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all Payment Status options", pstats_path %> (<%= @pstat.count %>) </li>
		<li><%=link_to "Add new Payment Status", new_pstat_path %></li>
		</ul>
		</div>

		<div class="square" id="ceight"> 
		<div class="consoleboxtitle"> Showcase Management </div>
		<ul class="consolebox">
		<li><%=link_to "Feature on Home Page", projects_path %> </li>
		</ul>
		</div>

	</div>

</div>

</div> <!-- end container -->

<% end %>

app/views/navigation/contact.html.erb
<div class="container-fluid" id="contactcontainer">



</div>

<div class="container" id="contactrelativecontainer">
<div class="map">

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7242.3947368657!2d67.058184!3d24.822923149999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33c4faae48deb%3A0xbc80e82cc4bfee8e!2sD.H.A.+Phase+4%2C+Karachi%2C+Pakistan!5e0!3m2!1sen!2s!4v1429568025196" width="600" height="450" frameborder="0" style="border:0"></iframe>

</div>

<div class="contactinfo">

<p class="attn"> Get in touch </p>

<ul class="listnolist">
	<li> Phone: 0345-306-7433</li>
	<li> Studio: E/24, 4th Gizri Street, Phase IV, DHA - Karachi, Pakistan </li>
	<li> Email: <%= mail_to "info@nadirtoosy.com", "Info@nadirtoosy.com", subject: "Inquiry"%> </li>
	<li> Facebook: <%= link_to "NTP on Facebook", "https://www.facebook.com/nadirtoosy", :target => "_blank"  %> </li>
	<li> Twitter: <%= link_to "NTP on Twitter", "https://www.twitter.com/nadirtoosy", :target => "_blank"  %></li>
</ul>

</div>

</div>
				
</div>

app/views/navigation/home.html.erb
<div class="container-fluid">


<div id="carousel1" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">

        <% @featuredprojects.each_with_index do |x, index| %>
        <% if index == 0 %> 
          <li data-target="#carousel1" data-slide-to="<%=index%>" class="active"></li>
        <% else %>
          <li data-target="#carousel1" data-slide-to="<%=index%>"></li>
        <% end %>
      <% end %>
          <% @featuredprojects.each_with_index do |x, index| %>
                <% y = x.photos.first %>
                 </ol>
                    <% if index == 0 %> 
                      <div class="carousel-inner center" role="listbox">
                      <div class="item active" id="carouselpictureframe">
                    <% else %>
                      <div class="item" id="carouselpictureframe">
                    <% end %>
                <%= image_tag(y.asset.url(:carousel), class: "carouselpicture") %>
              <div class="carousel-caption" id="carouselcaption">
              
                  <p class="carouseltext"> <span><%= x.headline %></span> </p>
                

         <%= link_to "View Set", project_photo_path(x, x.photos), class: "btn btn-default btn-sm viewset mb" %>
      </div>

      </div>

  <% end %>

  </div> <!-- Carousel-Inner  -->
    
    <!-- Carousel Navigation -->
    <a class="left carousel-control" href="#carousel1" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>
    <a class="right carousel-control" href="#carousel1" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> </a> 

    </div> <!-- Carousel1c -->

    <br>

    <div class="container" id="recentbody">

      <div class="spacerforhomepage">

        <p class="attn"> Recent Work </p>

      </div>

<div class="previewwork">




<div class="row">

  <% @z.each do |a| %>

      <div class="col-xs-6 col-sm-3">
            <% b = a.photos[0] %>
    <% if b.present? %>
    <div title="<%= a.client.name %>">
         <%= link_to(image_tag(b.asset.url(:preview)), project_photo_path(a, a.photos),  class: "recent") %> </div>
       </div>
        <% end %>
          <% end %>
     </div>




</div>

</div>

</div>

</div>


<script>
$('.carousel1').carousel()
</script>

</body>

app/views/navigation/instagram.html.erb
<div class="container" id="containerb">

<% @fi["data"]&.each do |object| %>

<div class="instaimage">

	<div class="imageblock"> <%= image_tag(object["images"]["standard_resolution"]["url"], size: "350x350") %> </div>

	<div class="likeblock"><span class="glyphicon glyphicon-thumbs-up"></span>  <%= object["likes"]["count"] %> </div>

</div>



<% end %>
</div>

<script>

var $container = $('#containerb').isotope({
  itemSelector: '.instaimage',
   masonry: {
    columnWidth: 20
  }
});

$container.imagesLoaded( function() {
  $container.isotope('layout');
});

$('.filter-button-group').on( 'click', 'button', function() {
  var filterValue = $(this).attr('data-filter');
  $container.isotope({ filter: filterValue });
});


</script>

app/views/navigation/work.html.erb
<div class="container-fluid" id="container">
  <div class="container-fluid">
    <p class="attn"> Work </p>
    <div class="button-group filter-button-group">
      <ul class="nav navbar-nav" id="submenu">
        <li><button class=" btn btn-xs btn-link" data-filter="*">Show all</button></li>
        <% @ctypes.each do |y| %>
       <li> <button class=" btn btn-xs btn-link" data-filter=".<%=y.name%>"><%=y.name%></button></li>
       <% end %>
     </div>
   </div> <!-- fluid -->
 </div> <!-- Z -->
 <div class="container-fluid" id="containerw">
  <div class="container-fluid" id="workbox">
    <% @projects.each do |x| %>
    <div class="Witem thumbnail <%= x.ctype %>">
      <% x.photos.first(1).each do |y| %>
      <%= image_tag(y.asset.url(:square)) %>
      <% end %>
      <h4 class="little" id="thumbnail-label"> <%= x.client.name %> </h4>
    </br>
    <div> Type: <%= x.ctype %> </div>
    <div> Location: <%= x.location %> </div>
  </br>
</br>
<%= link_to "View Set", project_photo_path(x, x.photos), class: "btn btn-default btn-sm viewset" %>
</br>
<div class="whr"></div>
</div> <!-- Witem -->
<% end %>
</div> <!-- workbox -->
</div> <!-- containerw -->

<script>

var $container = $('#workbox').isotope({
  itemSelector: '.Witem',
   masonry: {
    columnWidth: 225
  }
});

$container.imagesLoaded( function() {
  $container.isotope('layout');
});

$('.filter-button-group').on( 'click', 'button', function() {
  var filterValue = $(this).attr('data-filter');
  $container.isotope({ filter: filterValue });
});


</script>

app/views/navigation/x.html.erb
<div class="container" id="containerb">


<% if admin_signed_in? %>

<div> Admin Console </div>

<div class="row">

	<div class="col-md-6">
	</br>
		<p class="attn"> Projects by Category </p>
		<%= pie_chart Project.group(:ctype).count, colors: ["#52adc0", "#5276c0", "#52c09c", "#6552c0", "#9c52c0", "c052ad", "#c05276", "#c06552", "#c09c52"] %>
	</div>

	<div class="col-md-3">

		<div class="square" id="cone"> 
			<div class="consoleboxtitle"> Model Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all models", models_path %> (<%= @models.count %>) </li>
		<li><%=link_to "Add new model", new_model_path%></li>
		<li><%=link_to "Models preview page", preview_path%></li>
		</ul>
		</div>

		<div class="square" id="ctwo"> 
		<div class="consoleboxtitle"> Photographer Management</div>
		<ul class="consolebox">
		<li><%=link_to "View all photographers", photographers_path %> (<%= @photographers.count %>) </li>
		<li><%=link_to "Add new photographer", new_photographer_path%></li>
		</ul>
		</div>

		<div class="square" id="cthree"> 
		<div class="consoleboxtitle">  Client Management </div>
		<ul class="consolebox">
		<li><%= link_to "View all clients",    clients_path %> (<%= @clients.count %>) </li>
		<li><%=link_to "Add new client", new_client_path%></li>
		</ul>
		</div>

		<div class="square" id="cfour"> 
		<div class="consoleboxtitle"> Category Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all categories", ctypes_path %> (<%= @ctypes.count %>) </li>
		<li><%=link_to "Add new category", new_ctype_path %></li>
		</ul>
		</div>

	</div>

	<div class="col-md-3">

		<div class="square" id="cfive"> 
		<div class="consoleboxtitle"> Location Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all locations", locations_path %> (<%= @locations.count %>) </li>
		<li><%=link_to "Add new location", new_location_path %></li>
		</ul>
		</div>

		<div class="square" id="csix"> 
		<div class="consoleboxtitle"> Project Status Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all Statuses", statuses_path %> (<%= @statuses.count %>) </li>
		<li><%=link_to "Add new Status", new_status_path %></li>
		</ul>
		</div>

		<div class="square" id="cseven"> 
		<div class="consoleboxtitle"> Payment Status Management </div>
		<ul class="consolebox">
		<li><%=link_to "View all Payment Status options", pstats_path %> (<%= @pstat.count %>) </li>
		<li><%=link_to "Add new Payment Status", new_pstat_path %></li>
		</ul>
		</div>

		<div class="square" id="ceight"> 
		<div class="consoleboxtitle"> Featured Project Management </div>
		<ul class="consolebox">
		<li><%=link_to "Manage Featured Projects", projects_path %> </li>
		</ul>
		</div>

	</div>

</div>

</div> <!-- end container -->

<% end %>